### ISSUE TITLE
Support parameter default values.

### ISSUE THREAD

**Issue by iki** [kevinrenskers/raml2html#100]
The default value, if provided, could be displayed next to required/type information:

- **n**: *(integer)* *(default: 20)*

Of course, required and default will probably never be present together, as that combination does not make sense.

**Comment by kevinrenskers** [comment]
Good point. Can you perhaps provide a pull request with that change?

**Comment by iki** [comment]
Sure, will do that gladly.

**Comment by iki** [comment]
Many thanks, I did not got to it yet!
