### ISSUE TITLE
Unable to run raml2html on windows: Error: unknown protocol c:

### ISSUE THREAD

**Issue by balinju** [kevinrenskers/raml2html#102]
I have just installed raml2html using npm, and I cannot execute it on windows, I am getting the following error

```bash
$ raml2html -i dad-mobile.raml -o dad-mobile.html

C:\Users\Alan.Domain-LTD\AppData\Roaming\npm\node_modules\raml2html\node_modules\raml2obj\node_modules\raml-parser\lib\raml.js:46
          throw new exports.FileError("while reading " + file, null, "unknown
                ^
Error: unknown protocol c:
```

I have tried with -i and -o, I have also tried the > approach, I tried cygwin and command prompt, all give the same error.

I have also tried pre-pending my file names with file://C:/..., and I also tried hosting my file on HTTP and executed 

```bash
$ raml2html -i http://localhost:8081/raml
```

Still same issue.

**Comment by kevinrenskers** [comment]
This is a problem with the raml-js-parser: https://github.com/raml-org/raml-js-parser/issues/110. Once they release a new version it will also be fixed for raml2html. I'm sorry that I can't give you a quicker solution.

**Comment by abhshekkec322** [comment]
Do we have any idea about the planned date of this fix?

On which OS this converter works fine?

**Comment by kevinrenskers** [comment]
I don't know. They actually fixed the problem but haven't released it yet. See https://github.com/raml-org/raml-js-parser/pull/122.

raml2html works fine on Mac OS X and Linux.

**Comment by abhshekkec322** [comment]
Thanks for your quick response. I will wait till it get resolved.

**Comment by balinju** [comment]
Thanks for the information.

**Comment by abhshekkec322** [comment]
Today I saw the update from Dmartinezg that "It has been tagged and released as 0.8.10". Are you guys merging it? Please keep us posted when its resolved.

**Comment by kevinrenskers** [comment]
There is nothing to merge for me, raml2html indirectly uses any 0.8.x version of raml-js-parser. Running `npm update -g raml2html` should fix it for you, otherwise try uninstalling raml2html first and reinstall it.

**Comment by abhshekkec322** [comment]
Thanks.. It just worked.. :)

**Comment by kevinrenskers** [comment]
Hooray! :)
