### ISSUE TITLE
Unable to run raml2html on windows7: Error: unknown protocol c:

### ISSUE THREAD

**Issue by abhshekkec322** [kevinrenskers/raml2html#103]
Hi,
I have tried all of these commends but did not get success in generating HTML's from RAML's.
I tried example.raml as well after deleting example.html to make sure I am getting same issue.

Could you please advise if there is any fix available that I can use.

1.
C:\Users\rob>raml2html example.raml > example.html
C:\Users\rob\AppData\Roaming\npm\node_modules\raml2html\node_modules\raml2obj
\node_modules\raml-parser\lib\raml.js:46
          throw new exports.FileError("while reading " + file, null, "unknown
                ^
Error: unknown protocol c:

2.
C:\Users\rob>raml2html -i example.raml -o example.html
C:\Users\rob\AppData\Roaming\npm\node_modules\raml2html\node_modules\raml2obj
\node_modules\raml-parser\lib\raml.js:46
          throw new exports.FileError("while reading " + file, null, "unknown
                ^
Error: unknown protocol c:

3.
C:\Users\rob>raml2html -s -i example.raml -o example.html
C:\Users\rob\AppData\Roaming\npm\node_modules\raml2html\node_modules\raml2obj
\node_modules\raml-parser\lib\raml.js:46
          throw new exports.FileError("while reading " + file, null, "unknown
                ^
Error: unknown protocol c:

**Comment by kevinrenskers** [comment]
Please see #102.

**Comment by abhshekkec322** [comment]
Hi,

Is there any workaround until this issue is nit fixed?

Thanks

**Comment by kevinrenskers** [comment]
I'm afraid not.
