### ISSUE TITLE
Ability to add custom handlebars helpers

### ISSUE THREAD

**Issue by chmac** [kevinrenskers/raml2html#106]
Thanks for your work on raml2html, it's one of the main reasons we chose RAML over swagger. Having dug into the code a little, I see it's an extremely powerful tool. I copied the templates and swapped the example and schemas to put examples first. Took 5 minutes, thanks for making life easy. :+1: 

I'd like to (eventually) get around to rendering our JSON schemas a little more prettily. Is there any way I could use raml2html and add my own handlebars helper to render the JSON schema? I could fork the code and modify it directly, but that feels like a nightmare to maintain, etc.

If this is not currently possible, consider this a feature request. :-) You open to a PR if we implement this ourselves?

**Comment by dwcramer** [comment]
I've also found it necessary to add helpers and am already seeing how difficult it will be to merge in upstream changes, so a clean way to add helpers would be very nice!

**Comment by kevinrenskers** [comment]
Adding helpers is very easy as long as you use raml2html as a library (as opposed to running it from the command line which uses the default config and templates).

Please see https://github.com/kevinrenskers/raml2html/blob/master/examples/script.js for examples about running raml2html as a lib. The config object that you pass to raml2html.render simply needs a `helpers` object: https://github.com/kevinrenskers/raml2html/blob/master/lib/raml2html.js#L113

**Comment by kevinrenskers** [comment]
Of course if you want to modify the default templates with your own helpers yet at the same time stay up to date with upstream changes in the default templates.. I don't have a solution for that. You either use the supplied templates or you don't :)

Not sure if this answers your question? And yeah PR's are always welcome!

**Comment by kevinrenskers** [comment]
Closing this issue, please let me know if I can be of more help or if I misunderstood your question.

**Comment by tobilg** [comment]
Thanks for raml2html as well. I'm also interested in adding helpers. Could you maybe give an actual example on how a helper is passed via the `config` object?

**Comment by kevinrenskers** [comment]
The `raml2html.render` function needs a config object. That object can have a property called `helpers`, which is an object with named functions. Check how the `getDefaultConfig` function does it: https://github.com/kevinrenskers/raml2html/blob/master/lib/raml2html.js#L117-L158

So you could add to this..

```
var config = raml2html.getDefaultConfig();
config.helpers['mycustomhelper'] = function(options) { ... }
```

Or just create your own config object from scratch

```
var config = {
    template: '<h1>Hello!</h1>',
    helpers: {
        mycustomhelper: function(options) {
            ...
        }
    }
}
```

Please check the example script and the source code of raml2html as well.
