### ISSUE TITLE
Example for string fields are formatted as dates if they contain a date-like value

### ISSUE THREAD

**Issue by ddossot** [kevinrenskers/raml2html#109]
This RAML definition:

    queryParameters:
      from:
        description: Limit results to those created after from.
        example: 2014-12-31T00:00:00.000Z
        type: string
        required: false

Ends up rendered as:
```
Query Parameters
    from: (string)
    Limit results to those created after from.
    Example:
    Tue Dec 30 2014 16:00:00 GMT-0800 (PST)
```
The example should be `2014-12-31T00:00:00.000Z` not `Tue Dec 30 2014 16:00:00 GMT-0800 (PST)` since the field type is `string` not `date`.

**Comment by kevinrenskers** [comment]
This is a problem with raml-js-parser, I've reported it there: https://github.com/raml-org/raml-js-parser/issues/133. I'm hoping they will have a quick fix so that I don't have to create a workaround.

**Comment by ddossot** [comment]
OK, makes sense. Thanks for opening the issue! I'm tracking it now :+1:

**Comment by kevinrenskers** [comment]
Actually the workaround is easy: just put quotes around it. I looks kinda shitty with the syntax highlighting but at least you have the correct value.

**Comment by kevinrenskers** [comment]
Aaan the syntax highlighting is no longer a problem when the type is explicitly set to 'string'.

**Comment by ddossot** [comment]
Indeed wrapping with " solves the issue, even in the RAML API Console. Thanks!
