### ISSUE TITLE
pretty-print schema and examples for application/json mediatypes.

### ISSUE THREAD

**Issue by balthorium** [kevinrenskers/raml2html#111]
When RAML input contains schema or example contents in JSON-Schema, the results tend to come out like this:

![screen shot 2015-02-05 at 1 59 01 pm](https://cloud.githubusercontent.com/assets/5368409/6069478/c813e79e-ad41-11e4-94fd-d8ac5e14f0d1.png)

Would be nice if they looked more like this:

![screen shot 2015-02-05 at 1 59 28 pm](https://cloud.githubusercontent.com/assets/5368409/6069480/d14bd2fe-ad41-11e4-8c33-b73d6ead2897.png)

**Comment by balthorium** [comment]
Pull request #112 submitted to address this feature request :).

**Comment by kevinrenskers** [comment]
It's just shown however you input it in the raml file, for example:

![screen shot 2015-02-05 at 21 38 21](https://cloud.githubusercontent.com/assets/229384/6069838/8282a312-ad7f-11e4-94af-900c9c204239.png)

**Comment by kevinrenskers** [comment]
Closing this issue since there's a PR for this as well. The designs for version 2 of raml2html are almost done, so once that is (finally) implemented there's room for more improvements again. Sorry for the delays.

**Comment by balthorium** [comment]
Cool, thanks for the update and no worries on timing.
