### ISSUE TITLE
Can we add a synchronous method?

### ISSUE THREAD

**Issue by blakeembrey** [kevinrenskers/raml2html#114]
I need the synchronous render method for mounting this within a server. The only async part right now is the `raml2obj`, but I've already got the parsed RAML object.

**Comment by kevinrenskers** [comment]
raml2html.render uses raml2obj.parse, which calls raml-js-parser's raml.load or raml.loadFile, and those 2 are asynchronous. Nothing I can do about that, sorry.

Not sure what the problem is though, why does it need to be synchronous?

**Comment by blakeembrey** [comment]
> I've already got the parsed RAML object

We could have a method that accepted this object already, since everything I need is synchronous.

**Comment by blakeembrey** [comment]
@kevinrenskers For context, I rewrote https://github.com/mulesoft/osprey and am using this, but I already have the RAML object. I'd like to synchronously render the output so I can get rid of Osprey as a constructor taking a RAML file and allow it to accept any object.

**Comment by blakeembrey** [comment]
Ok, I just wanted to add it - but it's not possible without breaking backward compatibility because of the `config.processOutput` options which can be asynchronous. If we can remove that (or document that it's synchronous in the synchronous render), I'll be able to use this project again.

**Comment by kevinrenskers** [comment]
If you pass a RAML object then this code is executed: https://github.com/kevinrenskers/raml2obj/blob/master/raml2obj.js#L90-L93. If you use raml2html as a library (rather then from command line) you're free to create your own config object that doesn't contain an asynchronous processOutput function of course.

**Comment by blakeembrey** [comment]
Yes, it's still async. I'll do a PR and show what I could use. However, there's also jank `ramlObj.config = config` stuff going on. It'd be nice to not mutate the passed in object.

**Comment by blakeembrey** [comment]
@kevinrenskers By the way https://github.com/kevinrenskers/raml2obj/blob/master/raml2obj.js#L90-L96 and http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony, you're API is both synchronous and asynchronous.

**Comment by kevinrenskers** [comment]
Adding the config to the raml object means that it's accessible from the html templates. It's how I can render the raml2html version into the html for example. Not sure why it's a problem that the config object is added to it, simply don't render it if you don't want it?

Happy to see your PR.

**Comment by blakeembrey** [comment]
Actually, that doesn't look like a simple change since `minimize` is async. The config is an only issue because that object can be used anywhere, it's be not to mutate something you don't own. Config would be cleaner passed into handlebars as the data option so you can do `{{@whatever}}`.
