### ISSUE TITLE
Tagging endpoints as stable/deprecated/experimental via RAML traits.

### ISSUE THREAD

**Issue by balthorium** [kevinrenskers/raml2html#122]
Our team has found raml2html to be a really useful tool for generating docs from RAML, however we found we needed to be able to classify endpoints visually according to their relative stability.  This includes providing an appropriate icon in the summary view as well as text in the expanded view.

**Comment by kevinrenskers** [comment]
These traits are not a standard part of the RAML spec as far as I can tell, you're just making up traits. I don't think this should be part of raml2html, rather it feels like something you should keep in your own templates?

**Comment by kevinrenskers** [comment]
The raml spec should really support this, see this issue: https://github.com/raml-org/raml-spec/issues/132. 

I am closing this issue, coming up with custom traits seems like a slippery slope. You need stable/deprecated/experimental support, someone else needs something else, and before you know it raml2html supports a ton of custom traits all with their own icons and css colors and all that for one off use cases.

If many more people have the same use case I'd gladly reopen this ticket, but as this looks like a one off feature request I can't add this, sorry. Please use custom templates, I've tried to make that as simple to do as possible.

**Comment by balthorium** [comment]
I agree, this is a limitation of RAML.  It would be useful to support traits, though, as that is part of the spec.  Would you be open to something that documents traits in a more general way?

**Comment by kevinrenskers** [comment]
Yes, that sounds like a better idea.

**Comment by sichvoge** [comment]
Can I ask you to officially vote the candidate, please? Just +1 it :)
