### ISSUE TITLE
--output does not create missing directories

### ISSUE THREAD

**Issue by commonquail** [kevinrenskers/raml2html#128]
If the path given to `-o` includes a missing directory, [`fs.writeFileSync()`](https://nodejs.org/api/fs.html#fs_fs_writefilesync_filename_data_options) throws an unhandled (and undocumented...) error and `raml2html` exits successfully without producing any output.

```bash
$ ls
dummy.raml
$ raml2html --version
1.5.0
$ raml2html --input dummy.raml --output build/dummy.html
$ echo $?
0
$ ls
dummy.raml
```
If we make a quick change to see what's going on:
```javascript
try {
    fs.writeFileSync(program.output, result);
} catch (err) { console.log(err); }
```
```bash
$ raml2html --input dummy.raml --output build/dummy.html
{ [Error: ENOENT, no such file or directory 'build/dummy.html']
  errno: 34,
  code: 'ENOENT',
  path: 'build/dummy.html',
  syscall: 'open' }
```

[There are a few ways around this](http://stackoverflow.com/a/16317628/482758) but is it `raml2html`'s responsibility to ensure the path is valid? Arguments can be made both ways.

**Comment by kevinrenskers** [comment]
I think raml2html should at least return the error, I'll get this fixed asap.

**Comment by justjacksonn** [comment]
I would think raml2html could just create the directories instead.. if a user specifies them I would guess they mean for the directories to be there..or if not created?

**Comment by commonquail** [comment]
That would be the argument for. The argument against is the same as any other command that doesn't do that.

**Comment by kevinrenskers** [comment]
I think the user should make sure the directories exist. The error reporting will be fixed in the next version though!

**Comment by marianlopatnic** [comment]
Hello,
I support justJacksonn in his claim that raml2html should just create the directories if they don't exist or at least have the option to tell it to create it.
Please consider the following scenario:

the raml file is located at:
docs/v1/api.raml

i want to generate the html using maven-exec-plugin in the build process and have the html in :
target/projectBuildFinalName/docs/v1/api.html

so it will endup in the war file to be delivered along the api.

At the moment this is not possible without creating the docs/v1/ folder prior to invoking the maven-exec-plugin.

**Comment by kevinrenskers** [comment]
Isn't that what `mkdir -p` is perfect for? :)

If you really need it, please consider making a pull request with this change, thanks!

**Comment by marianlopatnic** [comment]
no, mkdir -p is not perfect for this because the build should be platform agnostic. 
What about Windows?
The build should run on development machines which usually run Windows as well as on CI environment which runs on a Linux flavor and I can't emphasize how much  i hate having maven profiles for environment specific crap.

**Comment by kevinrenskers** [comment]
Yes ok, of course the build script should run whatever command is appropriate for the platform. This was just an example. Like if I would run raml2html from the command line, I could prefix it with `mkdir -r whatever/you/want; raml2html...` and it works. No need for the tool itself to do it. The linux philosophy, do one thing and chain together different tools.

But it sounds like you have an itch to scratch, so like you I said: if you really need it please consider making a PR. Thanks!

**Comment by benishor** [comment]
No need for flames. How about making this behaviour configurable at runtime with an optional switch?

**Comment by kevinrenskers** [comment]
@benishor yep I would indeed do it via a `-c` / `--create-directories` parameter. If someone creates a PR with that, I'd merge it.

**Comment by marianlopatnic** [comment]
IMHO the tool itself needs to do it and actually needs to do it silently, running a md/mkdir etc. prior to running raml2html is implementation detail bleeding out of the api of using the raml2html:

**Comment by benishor** [comment]
@marianlopatnic actually wether the output directory should be created or not **is** part of the exposed API since it is a user-selected behaviour.

**Comment by marianlopatnic** [comment]
the exposed api atm does not allow the user to select the behavior, it just forces him to search through the raml documentation to find the hard way that there is no option to specify that the folders should be created and that actually he needs to create it by himself

**Comment by kevinrenskers** [comment]
Not sure we need to continue this discussion. Feel free to add an extra parameter to the CLI that will create directories as needed. Then you have what you want, so I don't really see the problem here.
