### ISSUE TITLE
Allow for more than one RAML input file

### ISSUE THREAD

**Issue by justjacksonn** [kevinrenskers/raml2html#132]
Currently, unless I am missing something, I can't add more than one raml file. Since the API Designer is too sluggish on larger RAML files, and it is also good design (or perhaps forced design) in larger companies to have multiple RAML files for different API product surfaces, it would be nice to specify multiple files of input and have raml2html generate the HTML for all of them in one go. More so, it would be great if it could render them all in one HTML file... OR optionally generate separate HTML files for each RAML input file. I do realize this latter option could be achieved by simply calling raml2html for each RAML file as well, and that is certainly an acceptable answer in this case, but I would still like to see all RAML files specified combined in to one html file.

**Comment by kevinrenskers** [comment]
You can do something like this, isn't that what you're after?

```
#%RAML 0.8
title: Example
version: 1
baseUri: http://example.com/{version}

/account: !include account.raml
/status: !include status.raml
/channels: !include channels.raml
/conversations: !include conversations.raml
/organisations: !include organisations.raml
/users: !include users.raml
/groups: !include groups.raml
/feeds: !include feeds.raml
/switches: !include switches.raml
/locations: !include locations.raml
/shifts: !include shifts.raml
/tasks: !include tasks.raml
/upload: !include upload.raml
```

So this way you have your separate files per top level resource. Actually rendering multiple RAML files into one HTML file is not on the todo list, it feels like not a lot of people would use since you already have this solution available to you.

Rendering multiple RAML files into multiple HTML files: yes, just call it multiple times or use raml2html as a library and write your own script that does just that.

**Comment by justjacksonn** [comment]
Just a comment on this... it appears that each separate RAML file can't be a valid RAML file to include it like you have here. It fails on each RAML file having title, baseUri, etc in it. So it appears I would have to put individual API surfaces in non-raml based files to include them as you have shown above.

**Comment by justjacksonn** [comment]
Ok..confirmed.. you can't include any of the root level stuff like schemas, traits, documentation, etc in each of the .raml files you want to include as you have done above. So it seems that using raml2html to allow a single html help system that covers multiple API surfaces (or products in my case) is not possible. It would require a bit of work to either build each HTML separately, then hand craft a connecting "home" page (not entirely a bad idea btw). Or build all the resources in non-RAML like fashion (in other words, either build it with all that stuff in place.. to use the IDE code completion and such and then remove it when ready to include it in a master file, or build it without the help of code completion).

Either way it's not a deal breaker, just involves a little more work finessing a single documentation page from multiple raml files.

**Comment by mvarshavsky** [comment]
@kevinrenskers - so is that the official stance? I'd love to keep documentation of top-level resources in its separate corresponding files just like you're suggesting - however, as @justjacksonn noted that would make them non-valid RAML files (losing the tooling along the way), right?

**Comment by kevinrenskers** [comment]
I'm no longer the lead maintainer, but since we rely on the official RAML parser, I think we should stick to what the spec supports.
