### ISSUE TITLE
please publish github version to npm

### ISSUE THREAD

**Issue by coderofsalvation** [kevinrenskers/raml2html#134]
Please do this because I was pulling my hair out.
This will result in a broken raml2html:

    npm install raml2html

It seems this works:

    npm install git://github.com/kevinrenskers/raml2html

I found out  the last version has the update which uses callbacks for the 'parse'-function of the raml2obj dependancy.

So either please freeze the raml2obj-version in package.json which npm uses, or just publish this github version to npm.
Npm is most people's go-to-place anyways.

Cheers

**Comment by kevinrenskers** [comment]
The current version of raml2html still uses raml2obj version 1: https://github.com/kevinrenskers/raml2html/blob/master/package.json#L17. The code that's in the master branch *is* published to npm.

**Comment by kevinrenskers** [comment]
Just did a clean npm install raml2html and everything seems to work just fine.

**Comment by coderofsalvation** [comment]
Ok, I did a clean install and I can confirm this.
Probably something weird was happening over here.
Closing issue.
