### ISSUE TITLE
xml schema not working

### ISSUE THREAD

**Issue by schnable** [kevinrenskers/raml2html#140]
I have a raml spec that is using XML for some interfaces;  the html generated document for the included xsd is simply dropping the xml document inline between pre tags, which is not properly displayed in the browser.  

Are there any plans to support embedded xsd schema files?

**Comment by kevinrenskers** [comment]
Ah right, should use html entities instead. I'll try to get to this asap.

**Comment by tgeraty** [comment]
+1  
I'm having the same problems showing xml examples and schema. Besides the xml problems, this is a very useful utility - love it.

**Comment by kevinrenskers** [comment]
Do you have an example raml file that uses XML examples and schemas?

**Comment by kevinrenskers** [comment]
Never mind, 2.0.2 was just published with a fix.

**Comment by tgeraty** [comment]
Awesome! Sorry I didn't get the example to you before you had a chance to work on it. Just checked out the latest and it works perfect. Thanks again for the quick response!

**Comment by schnable** [comment]
Thanks!   I've just downloaded it -  will be testing soon!

Andrew
