### ISSUE TITLE
Where are all my headers?

### ISSUE THREAD

**Issue by davidfells** [kevinrenskers/raml2html#142]
I see no headers in my docs at all! I'm using traits, resource types, and security schemes - and none of them appear in the raml2html generated docs.

**Comment by kevinrenskers** [comment]
I'm very surprised to hear that. Do you have an example RAML file for me? Which version of raml2html are you using? Are you using custom templates?

**Comment by davidfells** [comment]
No custom templates, latest raml2html (whatever comes from a current npm install). My RAML is broken into files, here's a zip: https://www.dropbox.com/s/5rx0o2u2r9iu1ug/Inmar_CDM-v1-2.zip?dl=0

Once you build it, you should see, for example, the global API key header defined in the unauthenticated security scheme. It works fine on Mulesoft Anypoint with the real time docs panel, I wonder what version of R2H they're using?

**Comment by kevinrenskers** [comment]
They are not using raml2html :)

I'll take a look at your example.

**Comment by davidfells** [comment]
Oh, I thought I saw it mentioned that they were, but I can't find that mention now.

**Comment by kevinrenskers** [comment]
That zip file seems empty to me. Can you just create a very basic example showing the problem, post it inline here?

**Comment by davidfells** [comment]
Sure.

I have a security scheme.
```
type: x-{other}
description: API Key only
describedBy:
  headers:
    X-Inmar-REST-API-Key:
      type: string
      description: Application API Key
  responses:
    471:
      body:
        application/json:
          schema: Error
          example: |
            {
              "code": "471",
              "message": "invalid api key"
            }
```

Used here...

```
securitySchemes:
  - Unauthenticated: !include securitySchemes/unauthenticated.raml
securedBy: [ Unauthenticated ]
```

THAT securedBy is global, but I'm using another one that's method scoped and it doesn't appear either. Neither do headers specified in my traits.

**Comment by kevinrenskers** [comment]
Thanks. So yeah, I'm afraid that the security schemes are not fully rendered, this is a known issue: #10. It's mainly because I have not needed any of the things you mentioned myself, so a pull request would be greatly appreciated :)

I am working on the develop branch to add more info to the rendering of the security schemes, for example the description. Help is very welcome.

**Comment by kevinrenskers** [comment]
In my testing I found that headers for traits are rendered. I have never used resourceTypes, so I'll need to find an example first.

**Comment by kevinrenskers** [comment]
Looking at the github example file I can see that they use resourceTypes and that those headers are also rendered correctly. So I'm closing this ticket as #10 should take care of the security schemes. If I missed anything feel free to reopen with an example raml file!

**Comment by davidfells** [comment]
Thanks Kevin. Here: https://www.dropbox.com/s/cybhy3l7ghyfexz/Inmar_CDM-v1-3.zip?dl=0

That file actually works!
