### ISSUE TITLE
!include does not work.

### ISSUE THREAD

**Issue by lolobosse** [kevinrenskers/raml2html#143]
Hi there,

I read the section `Before reporting a bug` but I think the output of the parser is ok because I tested it myself. I have a separate file in the same directory with my JSON Schemas. When I parse it with the js parser you're using, they appear as object in the console (I mean they're parsed perfectly).

When rendering it, I got an error:
```
Error parsing: while reading /Users/laurentmeyer/Documents/JobNinja%20Doc/API%20RAML/data-model.yaml cannot read /Users/laurentmeyer/Documents/JobNinja%20Doc/API%20RAML/data-model.yaml (Error: ENOENT, open 'path/API%20RAML/data-model.yaml') in "path/API RAML/api.raml", line 36, column 5
```
It is clear that it is a parsing error but I cannot understand why because, as I mentioned the parser works but I think there is a bug with the `%20` character, could it be? Does some of you have experience with these external JSON Schemas?

**Comment by kevinrenskers** [comment]
raml2html doesn't do any parsing, this error comes from raml-js-parser. I'm sorry but I can't help you, you'll have to report/ask [here](https://github.com/raml-org/raml-js-parser).

**Comment by kevinrenskers** [comment]
I would suggest to try it without spaces first..

**Comment by lolobosse** [comment]
Yes, that was it! The problem came from the fact that some folders where named with spaces! :tada: 

Ok, then, I do not know if it can be considered as a bug but I could be useful to put this little precision in the readme of the parser (but a reminder in yours cannot be bad :smile: :+1: ).

**Comment by kevinrenskers** [comment]
Looked at all the examples in http://raml.org/spec.html, and they always use `-` or something instead of spaces. If I were you I'd report this as a bug to https://github.com/raml-org/raml-js-parser and simply don't use spaces in paths.

**Comment by lolobosse** [comment]
Ok thanks for your time, I know that's bad practice but I find it looks better in the Finder :grin:
