### ISSUE TITLE
Misleading error message when the raml file does not exist

### ISSUE THREAD

**Issue by mik01aj** [kevinrenskers/raml2html#144]
Originally reported in https://github.com/raml-org/raml-js-parser/issues/153

When I run `raml2html` and point to an invalid file path, it produces this output:

```
Error parsing: version validation
The first line must be: '#%RAML 0.8'
  in "undefined", line 1, column 1
```

I would expect a message like "file not found".

**Comment by kevinrenskers** [comment]
This error is generated by raml-js-parser when you give it an invalid file. So the misleading error should be fixed by them.

**Comment by drernie** [comment]
I'm still seeing this error in raml2html --version
3.0.1

Has that picked up the new raml2obj that supposedly fixes this problem?

**Comment by kevinrenskers** [comment]
No.
