### ISSUE TITLE
Weird div overlay in Chrome

### ISSUE THREAD

**Issue by tewarid** [kevinrenskers/raml2html#148]
Especially in Chrome (but Safari has rendering issues too) the documentation towards the end of \<div class="page-header"\> overlays the content of the following divs (\<div class="panel panel-default"\>\<div class="panel-heading"\>...). Adding style="overflow: hidden" to the div seems to fix it [http://stackoverflow.com/questions/15693226/weird-div-overlay-on-chrome].

**Comment by tlkiong** [comment]
Can you provide more details such as screenshot as I am not viewing such issue
