### ISSUE TITLE
Disappearing scrollbar in Chrome

### ISSUE THREAD

**Issue by georgeproctor** [kevinrenskers/raml2html#152]
Hi there,

I totally love this tool, but I've found an issue with the generated HTML page in Chrome; when I click on a method to bring up the lightbox with the Request/Response details, then the page's scrollbar disappears after I close that window, and I can no longer scroll up and down the documentation. The only way to fix is to reload the page.

I'm running Google Chrome (45.0.2454.85 (64-bit)) on Linux Mint 17.1 (Cinnamon 2.4.8, 64-bit). I'm viewing the generated HTML file straight off the filesystem.

EDIT: I just checked the console and I think viewing the HTML from a local file is what's causing the problem. I got this error:

```
Uncaught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'file:///home/george/api.html#' cannot be created in a document with origin 'null'.
```

**Comment by caojianhua1741** [comment]
The same problem on me

**Comment by kevinrenskers** [comment]
I'll have a look soon but can you check if it also happens when running from a webserver? Just use https://www.npmjs.com/package/static-server to quickly start one from your current directory.

**Comment by caojianhua1741** [comment]
Thanks for your quickly reply, it's ok on the static-server. This problem only appeared when I open the html file as a local file.

**Comment by 111crb111** [comment]
it's caused by security reason 
```
Uncaught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'file:///D:/!my/temp/raml2html/example.html#' cannot be created in a document with origin 'null'.
```
My fix:
``` javascript
        // remove url fragment on modal hide
        $('.modal').on('hidden.bs.modal', function() {
          window.location.hash = '';
          // if(history && history.replaceState) {
          //   history.replaceState({}, '', '#');

          // }
        });
```
