### ISSUE TITLE
Every time when close the modal, the scroll goes back up to the top of the page

### ISSUE THREAD

**Issue by tlkiong** [kevinrenskers/raml2html#157]
Would be great if after close the modal, the scroll position remains the same

**Comment by kevinrenskers** [comment]
I don't have this problem at all. Which browser?

**Comment by tlkiong** [comment]
Erm, Chrome.

**Comment by kevinrenskers** [comment]
This is the example file shipped with raml2html: https://rawgit.com/kevinrenskers/raml2html/master/examples/example.html. Works totally fine for me. Do you have the issue here?

**Comment by tlkiong** [comment]
No. Could it be because I run mine from fs instead of from a server?

**Comment by kevinrenskers** [comment]
Hm yea I can reproduce it that way, and only on Chrome. Your PR is a bit.. hacky though, not too fond of solving it that way.

**Comment by tlkiong** [comment]
Hmm. What do you suggest?

**Comment by kevinrenskers** [comment]
Actually your change https://github.com/kevinrenskers/raml2html/pull/155 broke it. Before that you got the JS error in Chrome, but it didn't scroll to the top. Pretty sure that `window.location.hash = '';` is the cause. So I think we should solve the root problem properly.

**Comment by tlkiong** [comment]
Noted on that. Will check that out.
