### ISSUE TITLE
More granular page anchors

### ISSUE THREAD

**Issue by phonyphonecall** [kevinrenskers/raml2html#38]
Currently we can use page anchors to link to specific base resources. For example:

`/{dir}/example.html#_account` will link me to the specific account base resource:
![screen shot 2014-06-30 at 2 27 48 pm](https://cloud.githubusercontent.com/assets/5876159/3434686/fd6a4c10-008c-11e4-8012-ae1b816cde3c.png)

Being able to link to a specific action, on any specifc resource would be invaluavble for those looking to document large resource classes, withought duplicating documentation in the class implementation. Example:
`{host}/example.html#_account_find_get` would bring us to the following:
![screen shot 2014-06-30 at 2 27 34 pm](https://cloud.githubusercontent.com/assets/5876159/3434703/2c7ce576-008d-11e4-9188-005a586d769b.png)

Any feedback is welcome!

**Comment by eric-jahn** [comment]
I was just about to enter this same issue myself.  Thank you @phonyphonecall for agreeing to take this on.  Should be a fun little task.

**Comment by phonyphonecall** [comment]
@eric-jahn unfortunately I've swapped jobs since then, and am no longer using RAML. My mistake for leaving this issue hanging.

**Comment by zbycz** [comment]
I implemented this idea in #131 - comments welcomed.
