### ISSUE TITLE
Replace pop-ups with foldable sections

### ISSUE THREAD

**Issue by ddossot** [kevinrenskers/raml2html#97]
Maybe it's a matter of taste but I find the generated documentation a little too pop-up happy :smile:

Indeed, I think it would be easier to read if the method details were in foldable sections instead of pop-ups. Consider the case when you compare two methods: you have to go back and forth between pop-ups while, if foldable sections where used, you could see both information sections on the same page.

Thanks for considering this :smile_cat:

**Comment by kevinrenskers** [comment]
Yeah, this has been discussed multiple times before. I'm hoping to get a designer to make new default templates and this will definitely be part of the brief. Until then I'm not going to modify the default templates, sorry.

**Comment by ddossot** [comment]
Uh, OK. Strange you don't keep it open as an enhancement request...

**Comment by kevinrenskers** [comment]
You can add it to #89, that would be a lot easier for me.
